---
# tasks file for mysql (CentOS specific)

- name: Install MySQL server packages
  yum: name={{ item }} state=present
  with_items:
    - mysql
    - mysql-server
    - MySQL-python
  tags: mysql

- name: Create MySQL server configuration
  template: >
    src=my.cnf.j2
    dest={{ mysql_config_path }}
    owner=root
    group=root
    mode=0644
  notify: restart MySQL
  tags: mysql

- name: Ensure MySQL is running and enabled on boot
  service: name={{ mysql_daemon_name }} state=started enabled=yes
  tags: mysql

- name: Set the root password
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  when: ansible_hostname != "localhost"
  tags: mysql

- name: Set the root password
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  when: ansible_hostname == "localhost"
  tags: mysql
