---
# tasks file for mysql

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: mysql

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: mysql

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: mysql

- name: Create MySQL server configuration
  template: >
    src=my.cnf.j2
    dest={{ mysql_config_path }}
    owner=root
    group=root
    mode=0644
  notify: restart MySQL
  tags: mysql

- name: Ensure MySQL is running and enabled on boot
  service: name={{ mysql_service_name }} state=started enabled=yes
  tags: mysql

- name: Create root user MySQL client configuration
  template: >
    src=root_dot_my.cnf.j2
    dest=/root/.my.cnf
    owner=root
    group=root
    mode=0600
  tags: mysql

- name: Remove MySQL anonymous user
  mysql_user: name="" host={{ item }} state=absent
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  tags: mysql

- name: Remove MySQL test database
  mysql_db: name=test state=absent
  tags: mysql
