---
# tasks file for mysql (Ubuntu specific)

- name: Enter root password
  debconf: >
    name=mysql-server
    question='mysql-server/root_password'
    value={{ mysql_root_password }}
    vtype='password'
  tags: mysql

- name: Confirm root password
  debconf: >
    name=mysql-server
    question='mysql-server/root_password_again'
    value={{ mysql_root_password }}
    vtype='password'
  tags: mysql

- name: Install MySQL server packages
  apt: name={{ item }} state=present update_cache=true
  with_items:
    - mysql-server
    - python-mysqldb
  tags: mysql

- name: Create MySQL server configuration
  template: >
    src=my.cnf.j2
    dest={{ mysql_config_path }}
    owner=root
    group=root
    mode=0644
  notify: restart MySQL
  tags: mysql

- name: Ensure MySQL is running and enabled on boot
  service: name={{ mysql_daemon_name }} state=started enabled=yes
  tags: mysql
